export * from './onboarding'
export * from './highlightElements'
export * from './banners'
export * from './about-page'

export { default as emptyChartStubPath } from './empty-chart-stub.svg'
export { default as emptyWinrateGraphPath } from './empty-winrate-graph.svg'
export { default as notFoundBackgroundMobile } from './not-found-background-mobile.png'
export { default as gamePreviewPath } from './game-preview.png'
export { default as introBackgroundPath } from './intro-background.png'
export { default as referralProgramPath } from './referral-program.png'
export { default as registeredFriendsPath } from './registered-friends.png'
export { default as referralCupImagePath } from './referral-cup-image.png'
export { default as linkedTagPath } from './linked-tag.png'
export { default as notLinkedTagPath } from './not-linked-tag.png'
