FROM node:20.10-alpine AS build

ARG VITE_BACKEND_URL
ARG VITE_STAND

ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_STAND=${VITE_STAND}

WORKDIR /code
# Copy root tsconfig needed by apps
COPY tsconfig.base.json ./
# Copy app files
COPY apps/web3/ apps/web3/
WORKDIR /code/apps/web3
RUN npm ci
RUN npm run build

FROM nginx:alpine AS prod
WORKDIR /usr/share/nginx/html
COPY --from=build /code/apps/web3/dist .
COPY apps/web3/.github/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
