FROM node:20.10-alpine AS build

ARG VITE_BACKEND_URL
ARG VITE_STAND

ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_STAND=${VITE_STAND}

WORKDIR /code
COPY tsconfig.base.json ./
COPY apps/offchain/ apps/offchain/
WORKDIR /code/apps/offchain
RUN npm ci
RUN npm run build

FROM nginx:alpine AS prod
WORKDIR /usr/share/nginx/html
COPY --from=build /code/apps/offchain/dist .
COPY apps/offchain/.github/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
